version: '3.8'

services:
  api:
    build:
      context: ./api  
    container_name: appwebmanga-api
    volumes:
      - ./api:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - appnet
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=AppManga
      - DB_USERNAME=postgres
      - DB_PASSWORD=12345678

  gui:
    build:
      context: ./gui  
    container_name: appwebmanga-gui
    volumes:
      - ./gui:/app
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - appnet

  db:
    image: postgres:16
    container_name: appwebmanga-db
    environment:
      - POSTGRES_DB=AppManga
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  postgres_data:
    driver: local
