version: "3.1"

services:
  Manga:
    image: postgres:16
    env_file: 
      - api/.env
    environment:
    
      POSTGRES_DB: AppManga
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  gui:
    image: node:20-alpine
    working_dir: /app
    command: "npm run start"
    volumes:
      - ./gui:/app
    ports:
      - 3000:3000
    depends_on:
      - Manga

  api:
    build: ./api
    working_dir: /var/www/
    volumes:
      - ./api:/var/www/
    ports:
      - 8000:8000
    depends_on:
      - Manga
    command: php artisan serve --host=0.0.0.0 --port=8000